# Site settings
title: Nikola Todorovic - NZT
description: NZT
# baseurl: "" # the subpath of your site, e.g. /blog
# url: nzt48.github.io  # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nikola Todorovic
user_description: I'm studying Computer Engineering and Information Theory at School of Electrical Engineering, University of Belgrade. I'm executive editor of LiBRE!, magazine about free software.  And I'm member of Haklab, Belgrade Hackerspace.
user_title: Software Engineer
email: nzt@fsfe.org
twitter_username: nzt_1A
github_username:  NZT48
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
